FROM openjdk:17
MAINTAINER "soumya <thesoumyabratac@gmail.com>"
COPY target/BootRestDockApp-3.3.4.jar  /usr/app/
WORKDIR /usr/app/
#EXPOSE 8080
ENTRYPOINT ["java", "-jar", "BootRestDockApp-3.3.4.jar"]